require_relative '../../lib/string_helper'

namespace :build do

  def camelize(snake_case_string)
    snake_case_string.split('_').collect(&:capitalize).join
  end

  desc 'Build use case markdown'
  task :use_cases do
    # Page that links to use cases.
    File.open('use_cases.md', 'w') do |use_case_file|
      use_case_file.puts(<<EOT
# Use Cases

EOT
      )
      dir_path = File.dirname(__FILE__)
      Dir.chdir(dir_path) do
        use_case_dirs = {
            :include => %w/
                reuse_text
                nest_inclusions
                include_markdown
                include_code_block
                include_highlighted_code
                include_page_toc
                include_text_as_details
                include_text_as_comment
                include_text_as_pre
                include_generated_text
                include_with_added_comments
                diagnose_missing_includee
                diagnose_circular_includes
            /,
            :run_irb => %w/
                run_irb
            /
        }
        use_case_dirs.each_pair do |section, dir_names|

          # Header for section, if any dirs therein.
          title = StringHelper.to_title(section.to_s).sub(/ toc$/i, ' TOC')
          use_case_file.puts(<<EOT
## #{title}

EOT
) unless dir_names.empty?

          # Be careful with use case that has a backtrace.
          backtrace_cases = %w/
              diagnose_missing_includee
              diagnose_circular_includes
          /

          # Each use case is in a separate directory.
          dir_names.each do |dir_name|
            Dir.chdir("#{section}/#{dir_name}") do
              if File.exist?('includer.md')
                command = "markdown_helper #{section} --pristine includer.md included.md"
                if backtrace_cases.include?(dir_name)
                  # Capture the exception.
                  command += " 2> #{dir_name}.err"
                  # Generate the error.
                  begin
                    system(command)
                  rescue
                    #
                  end
                else
                  system(command)
                end
              end
              if File.exist?('template.md')
                command = "markdown_helper #{section} --pristine template.md markdown.md"
                system(command)
              end
              command = 'markdown_helper include --pristine use_case_template.md use_case.md'
              system(command)

              title_line = File.open('use_case_template.md').grep(/^#/).first.chomp
              title = title_line.split(/\s/, 2).pop
              use_case_file_name = File.basename('use_case.md')
              use_case_anchor = dir_name.gsub('_', '-')
              use_case_relative_url = File.join(
                  section.to_s,
                  dir_name,
                  use_case_file_name + '#' + use_case_anchor,
              )
              use_case_file.puts("* [#{title}](#{use_case_relative_url})")
            end
          end
        end
      end
    end
  end

end
